from pathlib import Path
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt


# ============================================================
# Configuration
# ============================================================

RESULTS_DIR = Path("results")

# Combined CSV files generated by opp_scavetool.
CSV_PATTERN = "*_metrics.csv"


# ============================================================
# Helpers
# ============================================================

def parse_iteration_vars(value):
    """
    Parse an OMNeT++ iterationvars string such as:

        $numSensors=10, $simTime=30s, $txPower=2.24mW,
        $sendInterval=1s, $packetLength=10Byte

    into a dictionary.
    """
    result = {}

    if pd.isna(value):
        return result

    for item in str(value).split(","):
        item = item.strip()

        if item.startswith("$"):
            item = item[1:]

        if "=" not in item:
            continue

        key, val = item.split("=", 1)
        result[key.strip()] = val.strip()

    return result


def numeric_value(series):
    """Convert a pandas Series to numeric values."""
    return pd.to_numeric(series, errors="coerce")


# ============================================================
# Process one combined scavetool CSV
# ============================================================

def process_file(filename):

    df = pd.read_csv(filename)

    # --------------------------------------------------------
    # Run information
    # --------------------------------------------------------

    runattrs = (
        df[df["type"] == "runattr"]
        .set_index("attrname")["attrvalue"]
        .to_dict()
    )

    run_name = runattrs.get("configname", filename.stem)

    iteration_vars = parse_iteration_vars(
        runattrs.get("iterationvars", "")
    )

    mac = runattrs.get("experiment", run_name)

    num_sensors = int(iteration_vars.get("numSensors", 0))
    tx_power = iteration_vars.get("txPower", "")
    send_interval = iteration_vars.get("sendInterval", "")
    packet_length = iteration_vars.get("packetLength", "")
    sim_time = iteration_vars.get("simTime", "")

    # --------------------------------------------------------
    # Packets sent
    # --------------------------------------------------------

    sent = df[
        (df["type"] == "scalar") &
        (df["name"] == "packetSent:count") &
        (df["module"].str.contains(
            r"\.sensor\[\d+\]\.app\[0\]$",
            regex=True,
            na=False
        ))
    ]

    packets_sent = numeric_value(sent["value"]).sum()

    # --------------------------------------------------------
    # Packets received
    # --------------------------------------------------------

    received = df[
        (df["type"] == "scalar") &
        (df["module"] == "AgricultureNetwork.server.app[0]") &
        (df["name"] == "packetReceived:count")
    ]

    packets_received = numeric_value(received["value"]).sum()

    # --------------------------------------------------------
    # PDR
    # --------------------------------------------------------

    if packets_sent > 0:
        pdr = packets_received / packets_sent * 100
    else:
        pdr = np.nan

    # --------------------------------------------------------
    # End-to-end delay
    # --------------------------------------------------------

    delay = df[
        (df["type"] == "vector") &
        (df["module"] == "AgricultureNetwork.server.app[0]") &
        (df["name"] == "endToEndDelay:vector")
    ]

    delay_values = numeric_value(delay["vecvalue"])

    mean_e2e_delay = delay_values.mean()

    # --------------------------------------------------------
    # Throughput
    # --------------------------------------------------------

    throughput = df[
        (df["type"] == "vector") &
        (df["module"] == "AgricultureNetwork.server.app[0]") &
        (df["name"] == "throughput:vector")
    ]

    throughput_values = numeric_value(throughput["vecvalue"])

    mean_throughput = throughput_values.mean()

    # --------------------------------------------------------
    # Sensor radio power
    # --------------------------------------------------------

    sensor_power = df[
        (df["type"] == "vector") &
        (df["module"].str.contains(
            r"AgricultureNetwork\.sensor\[\d+\]\.wlan\[0\]\.radio\.energyConsumer$",
            regex=True,
            na=False
        )) &
        (df["name"] == "powerConsumption:vector")
    ]

    sensor_power_values = numeric_value(sensor_power["vecvalue"])

    mean_sensor_power = sensor_power_values.mean()

    # --------------------------------------------------------
    # Gateway radio power
    # --------------------------------------------------------

    gateway_power = df[
        (df["type"] == "vector") &
        (df["module"] ==
         "AgricultureNetwork.gateway.wlan[0].radio.energyConsumer") &
        (df["name"] == "powerConsumption:vector")
    ]

    gateway_power_values = numeric_value(gateway_power["vecvalue"])

    mean_gateway_power = gateway_power_values.mean()

    # --------------------------------------------------------
    # Result row
    # --------------------------------------------------------

    return {
        "MAC": mac,
        "numSensors": num_sensors,
        "simTime": sim_time,
        "txPower": tx_power,
        "sendInterval": send_interval,
        "packetLength": packet_length,

        "packetsSent": packets_sent,
        "packetsReceived": packets_received,
        "PDR_percent": pdr,

        "meanE2EDelay": mean_e2e_delay,
        "meanThroughput": mean_throughput,

        "meanSensorRadioPower": mean_sensor_power,
        "meanGatewayRadioPower": mean_gateway_power,

        "sourceFile": filename.name,
    }


# ============================================================
# Process all result files
# ============================================================

def main():

    files = sorted(RESULTS_DIR.glob(CSV_PATTERN))

    if not files:
        print("No metric CSV files found.")
        return

    results = []

    for file in files:
        print(f"Processing {file.name}")

        try:
            results.append(process_file(file))
        except Exception as e:
            print(f"ERROR processing {file.name}: {e}")

    results_df = pd.DataFrame(results)

    results_df.to_csv(
        RESULTS_DIR / "all_metrics.csv",
        index=False
    )

    print()
    print("Final results:")
    print(results_df.to_string(index=False))

    # ========================================================
    # Graphs
    # ========================================================

    plot_metric(
        results_df,
        "PDR_percent",
        "Packet Delivery Ratio",
        "PDR (%)",
        RESULTS_DIR / "pdr_comparison.png"
    )

    plot_metric(
        results_df,
        "meanE2EDelay",
        "Mean End-to-End Delay",
        "Delay (s)",
        RESULTS_DIR / "e2e_delay_comparison.png"
    )

    plot_metric(
        results_df,
        "meanThroughput",
        "Mean Throughput",
        "Throughput (bps)",
        RESULTS_DIR / "throughput_comparison.png"
    )

    plot_metric(
        results_df,
        "meanSensorRadioPower",
        "Mean Sensor Radio Power",
        "Power (W)",
        RESULTS_DIR / "sensor_power_comparison.png"
    )

    plot_metric(
        results_df,
        "meanGatewayRadioPower",
        "Mean Gateway Radio Power",
        "Power (W)",
        RESULTS_DIR / "gateway_power_comparison.png"
    )


# ============================================================
# Plotting
# ============================================================

def plot_metric(df, metric, title, ylabel, output):

    plt.figure(figsize=(10, 6))

    # For now, group by MAC for the baseline comparison.
    grouped = (
        df.groupby("MAC")[metric]
        .mean()
        .sort_values()
    )

    grouped.plot(kind="bar")

    plt.title(title)
    plt.ylabel(ylabel)
    plt.xlabel("MAC protocol")
    plt.xticks(rotation=0)

    plt.tight_layout()
    plt.savefig(output, dpi=200)
    plt.close()


if __name__ == "__main__":
    main()