
#  ⢠⣾⠿⢷⣄⣀⣠⠤⣤⠢⣤⣾⠏⣤⢹⡇
#  ⣼⣿⢸⣶⡝⣿⣿⣷⡘⣧⣸⣿⣾⣿⢸⡧
#⢀⣽⣿⢸⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣦
#⢸⣿⣿⣿⣿⣿⣿⡿⠛⢻⣿⣿⣿⣿⠁⠈⣿⣿⠷⡄  mewlma
#⢸⣿⣟⠻⠿⣿⣿⣧⣀⣠⣿⣿⣿⣿⣶⣾⣿⣥⡾⡇
#⢸⣿⠿⠿⢶⣾⣿⣿⣿⣿⣿⣿⠟⢻⡿⢻⣿⣿⠶⡇
#⢸⣿⣶⣶⣶⠾⣿⣿⣿⣦⣍⣥⣾⣷⣶⣿⣿⣿⣷⠆
#⢸⣿⣿⣋⣥⣾⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣏
#⢸⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿
#⠈⠉⠉⠉

[General]
abstract = true
simtime-resolution = ps
**.vector-recording = true
**.scalar-recording = true
**.param-recording = false
**.packetReceived:count.scalar-recording = true
**.residualEnergyCapacity:last.scalar-recording = true
**.endToEndDelay:mean.scalar-recording = true
**.throughput:mean.scalar-recording = true

# misc
**.arp.typename = "GlobalArp"
*.gateway.forwarding = true
**.maxTransmissionDuration = 100ms

# configurator
*.configurator.addStaticRoutes = true
*.configurator.config = xmldoc("config.xml")

# radio and radioMedium
**.radio.centerFrequency = 2.45GHz
**.radio.bandwidth = 2.8MHz

**.radio.transmitter.bitrate = 19200 bps
**.radio.transmitter.headerLength = 8b
**.radio.transmitter.preambleDuration = 0.0001s

**.radio.receiver.energyDetection = -90dBm
**.radio.receiver.sensitivity = -100dBm
**.radio.receiver.snirThreshold = -8dB

*.radioMedium.backgroundNoise.power = -110dBm

**.wlan[*].mac.headerLength = 8b

# Sensor deployment
*.sensor[*].mobility.typename = "StationaryMobility"
*.sensor[*].mobility.initFromDisplayString = false
*.sensor[*].mobility.updateFromDisplayString = false

*.sensor[*].mobility.initialX = uniform(50m,550m)
*.sensor[*].mobility.initialY = uniform(50m,550m)
*.sensor[*].mobility.initialZ = 0m

# Gateway position
*.gateway.mobility.typename = "StationaryMobility"
*.gateway.mobility.initFromDisplayString = false
*.gateway.mobility.updateFromDisplayString = false

*.gateway.mobility.initialX = 300m
*.gateway.mobility.initialY = 300m
*.gateway.mobility.initialZ = 0m

# app
*.sensor[*].numApps = 1
*.sensor[*].app[0].typename = "UdpBasicApp"
*.sensor[*].app[0].destAddresses = "server"
*.sensor[*].app[0].destPort = 1000
*.sensor[*].app[0].startTime = exponential(1s)

*.server.numApps = 1
*.server.app[0].typename = "UdpSink"
*.server.app[0].localPort = 1000

# visualizer
*.visualizer.routingTableVisualizer.displayRoutingTables = false
*.visualizer.routingTableVisualizer.displayRoutesIndividually = false
*.visualizer.routingTableVisualizer.lineShift = 0
*.visualizer.routingTableVisualizer.displayLabels = false

*.visualizer.infoVisualizer.modules = "*.server.app[0]"
*.visualizer.infoVisualizer.format = "%t"

*.visualizer.networkRouteVisualizer.displayRoutes = true
*.visualizer.physicalLinkVisualizer.displayLinks = false

# configs

[Config Base]   
abstract = true
network = AgricultureNetwork
# Experiment variables
*.numSensors = ${numSensors=10}
sim-time-limit = ${simTime=30s}
#**.radio.transmitter.power = ${txPower=2.24mW}
*.sensor[*].app[0].sendInterval = ${sendInterval=1s}
*.sensor[*].app[0].messageLength = ${packetLength=10Byte}

[Config Ieee802154]
extends = Base
*.wlan[*].typename = "Ieee802154NarrowbandInterface"
*.radioMedium.typename = "Ieee802154NarrowbandScalarRadioMedium"
*.wlan[*].radio.signalAnalogRepresentation = "scalar"
*.wlan[*].radio.transmitter.power = ${txPower=2.24mW}

[Config BMac]
extends = Base

# Wireless interface
*.wlan[*].typename = "WirelessInterface"
*.wlan[*].radio.typename = "ApskRadio"
*.wlan[*].radio.signalAnalogRepresentation = "scalar"
# Radio and radio medium
*.radio.centerFrequency = 2.45GHz
*.radio.bandwidth = 2.8MHz
*.radio.transmitter.bitrate = 19200bps
*.radio.transmitter.headerLength = 8b
*.radio.transmitter.preambleDuration = 0.0001s
*.radio.transmitter.power = ${txPower=2.24mW}
*.radio.receiver.energyDetection = -90dBm
*.radio.receiver.sensitivity = -100dBm
*.radio.receiver.snirThreshold = -8dB
*.radioMedium.backgroundNoise.power = -110dBm

**.wlan[*].mac.typename = "BMac"
**.wlan[*].mac.headerLength = 1B
**.wlan[*].mac.slotDuration = 0.025s
**.wlan[*].queue.typename = "DropTailQueue"
**.wlan[*].queue.packetCapacity = 20

[Config XMac]
extends = Base
# Wireless interface
*.wlan[*].typename = "WirelessInterface"
*.wlan[*].radio.typename = "ApskRadio"
*.wlan[*].radio.signalAnalogRepresentation = "scalar"
# Radio and radio medium
*.radio.centerFrequency = 2.45GHz
*.radio.bandwidth = 2.8MHz
*.radio.transmitter.bitrate = 19200bps
*.radio.transmitter.headerLength = 8b
*.radio.transmitter.preambleDuration = 0.0001s
*.radio.transmitter.power = ${txPower=2.24mW}
*.radio.receiver.energyDetection = -90dBm
*.radio.receiver.sensitivity = -100dBm
*.radio.receiver.snirThreshold = -8dB
*.radioMedium.backgroundNoise.power = -110dBm

**.wlan[*].mac.typename = "XMac"
**.wlan[*].mac.headerLength = 1B
*.gateway.wlan[*].mac.slotDuration = 0.1s
*.sensor[*].wlan[*].mac.slotDuration = 0.25s
**.wlan[*].queue.typename = "DropTailQueue"
**.wlan[*].queue.packetCapacity = 20

[Config LMac]
extends = Base
# Wireless interface
*.wlan[*].typename = "WirelessInterface"
*.wlan[*].radio.typename = "ApskRadio"
*.wlan[*].radio.signalAnalogRepresentation = "scalar"
# Radio and radio medium
*.radio.centerFrequency = 2.45GHz
*.radio.bandwidth = 2.8MHz
*.radio.transmitter.bitrate = 19200bps
*.radio.transmitter.headerLength = 8b
*.radio.transmitter.preambleDuration = 0.0001s
*.radio.transmitter.power = ${txPower=2.24mW}
*.radio.receiver.energyDetection = -90dBm
*.radio.receiver.sensitivity = -100dBm
*.radio.receiver.snirThreshold = -8dB
*.radioMedium.backgroundNoise.power = -110dBm

**.wlan[*].mac.typename = "LMac"
**.mac.slotDuration = 50ms
**.mac.numSlots = 8
**.mac.reservedMobileSlots = 0
**.wlan[*].queue.typename = "DropTailQueue"
**.wlan[*].queue.packetCapacity = 10

# experiment configs
# variable: number of sensors
[Config Ieee802154_NumSensors]
extends = Ieee802154
*.numSensors = ${10,20,50,100}
#repeat = 5
#seed-set = ${repetition}

[Config BMac_NumSensors]
extends = BMac
*.numSensors = ${10,20,50,100}
#repeat = 5
#seed-set = ${repetition}

[Config XMac_NumSensors]
extends = XMac
*.numSensors = ${10,20,50,100}
#repeat = 5
#seed-set = ${repetition}

[Config LMac_NumSensors]
extends = LMac
*.numSensors = ${10,20,50,100}
#repeat = 5
#seed-set = ${repetition}

# variable: transmition power
[Config Ieee802154_TxPower]
extends = Ieee802154
*.wlan[*].radio.transmitter.power = ${1mW,2.24mW,5mW,10mW}
#repeat = 5
#seed-set = ${repetition}

[Config BMac_TxPower]
extends = BMac
**.radio.transmitter.power = ${1mW,2.24mW,5mW,10mW}
#repeat = 5
#seed-set = ${repetition}

[Config XMac_TxPower]
extends = XMac
**.radio.transmitter.power = ${1mW,2.24mW,5mW,10mW}
#repeat = 5
#seed-set = ${repetition}

[Config LMac_TxPower]
extends = LMac
**.radio.transmitter.power = ${1mW,2.24mW,5mW,10mW}
#repeat = 5
#seed-set = ${repetition}

# variable: send intervals 
[Config Ieee802154_Traffic]
extends = Ieee802154
.sensor[].app[0].sendInterval = ${0.5s,1s,2s,5s}
#repeat = 5
#seed-set = ${repetition}

[Config BMac_Traffic]
extends = BMac
*.sensor[*].app[0].sendInterval = ${0.5s,1s,2s,5s}
#repeat = 5
#seed-set = ${repetition}

[Config XMac_Traffic]
extends = XMac
*.sensor[*].app[0].sendInterval = ${0.5s,1s,2s,5s}
#repeat = 5
#seed-set = ${repetition}

[Config LMac_Traffic]
extends = LMac
*.sensor[*].app[0].sendInterval = ${0.5s,1s,2s,5s}
#repeat = 5
#seed-set = ${repetition}

# variable: packet size
[Config Ieee802154_PacketLength]
extends = Ieee802154
.sensor[].app[0].messageLength = ${32B,64B,128B,256B}
#repeat = 5
#seed-set = ${repetition}

[Config BMac_PacketLength]
extends = BMac
*.sensor[*].app[0].messageLength = ${32B,64B,128B,256B}
#repeat = 5
#seed-set = ${repetition}

[Config XMac_PacketLength]
extends = XMac
*.sensor[*].app[0].messageLength = ${32B,64B,128B,256B}
#repeat = 5
#seed-set = ${repetition}

[Config LMac_PacketLength]
extends = LMac
*.sensor[*].app[0].messageLength = ${32B,64B,128B,256B}
#repeat = 5
#seed-set = ${repetition}
